theme: minima
title: Who Am I?
author: Wesley Situ
email: kimgaaming49@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Keep things simple, stupid (KISS). 

# social links
twitter_username: I have None # DO NOT include the @ character, or else the build will fail!
github_username:  WesleySitu49 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
